In [304]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
df = pd.read_csv("yellow_cab_data.csv")
df = df.dropna()

In [275]:
time = []

for i in range(df.shape[0]):
    start = datetime.datetime.strptime(df.tpep_pickup_datetime[i], '%Y-%m-%d %H:%M:%S')
    end = datetime.datetime.strptime(df.tpep_dropoff_datetime[i], '%Y-%m-%d %H:%M:%S')
    time.append((end - start).total_seconds())

In [288]:
def lapace_pdf(x,loc, scale):
    return (1/(2*scale)) * np.exp(-abs(x-loc)/scale)
# D.shape[0]-1

def RMSE(x,y):
    return np.sqrt(np.mean((x-y)**2))

In [276]:
df["time"] = time
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,time
0,2,2022-01-01 00:17:55,2022-01-01 00:27:45,1.0,4.22,1.0,N,138,92,2,14.0,0.5,0.5,0.00,0.0,0.3,16.55,0.0,1.25,590.0
1,2,2022-01-01 00:22:03,2022-01-01 00:25:37,1.0,0.69,1.0,N,236,262,1,4.5,0.5,0.5,1.66,0.0,0.3,9.96,2.5,0.00,214.0
2,2,2022-01-01 00:52:33,2022-01-01 00:58:07,1.0,0.87,1.0,N,141,229,1,5.5,0.5,0.5,2.32,0.0,0.3,11.62,2.5,0.00,334.0
3,2,2022-01-01 00:31:12,2022-01-02 00:00:58,1.0,3.03,1.0,N,79,261,2,15.0,0.5,0.5,0.00,0.0,0.3,18.80,2.5,0.00,84586.0
4,2,2022-01-01 00:05:26,2022-01-01 00:29:05,1.0,4.56,1.0,N,50,79,1,18.5,0.5,0.5,4.46,0.0,0.3,26.76,2.5,0.00,1419.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145714,2,2022-01-31 23:00:46,2022-01-31 23:04:18,1.0,1.14,1.0,N,239,151,1,5.5,0.5,0.5,2.32,0.0,0.3,11.62,2.5,0.00,212.0
145715,1,2022-01-31 23:54:45,2022-02-01 00:03:20,0.0,2.00,1.0,N,246,163,1,8.5,3.0,0.5,2.45,0.0,0.3,14.75,2.5,0.00,515.0
145716,1,2022-01-31 23:56:23,2022-02-01 00:04:27,1.0,1.70,1.0,N,249,107,1,8.0,3.0,0.5,1.00,0.0,0.3,12.80,2.5,0.00,484.0
145717,1,2022-01-31 23:01:07,2022-01-31 23:05:28,0.0,0.40,1.0,N,239,143,1,4.5,3.0,0.5,1.66,0.0,0.3,9.96,2.5,0.00,261.0
145718,1,2022-01-31 23:24:28,2022-01-31 23:32:47,1.0,1.50,1.0,N,163,143,2,7.5,3.0,0.5,0.00,0.0,0.3,11.30,2.5,0.00,499.0

In [297]:
print(datetime.datetime.now())
D = df
answer = []
for i in np.random.randint(0,D.shape[0]-1,10):
    D1 = df.drop(df.index[i])
    new = df.iloc[i,:]
    #####
    x = np.array(D[["trip_distance", "time","passenger_count","RatecodeID"]])

    y = D.fare_amount
    #####
    x1 = np.array(D1[["trip_distance", "time","passenger_count","RatecodeID"]])
    y1 = D1.fare_amount
    ####
    new1 = np.array(new[["trip_distance", "time","passenger_count","RatecodeID"]]).reshape(-1,4)
    new1_y = new.fare_amount
    ####
    regr1 = RandomForestRegressor(n_estimators = 10, random_state = 42)
    regr1.fit(x, y)

    regr2 = RandomForestRegressor(n_estimators = 10, random_state = 42)
    regr2.fit(x1, y1)
    #print(regr2.predict([[0.91,300, 1, 1]])[0])
    #print(RMSE(regr2.predict(new1)[0], new1_y))

    ratio = lapace_pdf(new1_y,regr1.predict(new1)[0],1)/lapace_pdf(new1_y,regr2.predict(new1)[0],1)
    epsilon = np.log(ratio)
    answer.append(epsilon)

print(datetime.datetime.now())

2023-02-11 16:04:28.111256
2023-02-11 16:05:16.892654

## Epsilon *$\epsilon$*

In [300]:
np.median(answer)

0.10499999999999864